#### Numpy -> Used for Arrays in Python
       Intallation process - pip install numpy

       # numpy full forn-> numerical python
       # numpy array are 50 times faster than list

In [1]:
import numpy as np

#### Initialization of numpy array
    ar1 = numpy.array([1,2,3,4,5])
        or
    ar1 = np.array([1,2,3,4,5])  since using alias 

    #Precedence order of data type in array
      -> string > complex > float > int > bool
      -> if higher precedence order data is present then all data in array it will convert

In [4]:
ar1 = np.array([1,2,3,4,5])
print(ar1)

print(type(ar1))  # return type 

ar2 = np.array([1,2,3,4,'a'])
print(ar2) # all data covert to string 

[1 2 3 4 5]
<class 'numpy.ndarray'>
['1' '2' '3' '4' 'a']


#### Function define Shape & Size of Array
    # np.zeros([3,2])  or np.zeros([m,n])
      -> creates array of size 3X2 filled with float 0. 

    # np.random.random([3,2]) or np.random.random([m,n])
      -> creates array of size 3X2 having random number b/w 0 to 1
    
    # np.random.randint(1,10) or (m,n) range can be any
     -> generate single random value b/w 1 and 10

    # np.random.randomint(1,10,[3,4]) or (range,[m,n])
     -> generate array of size 3X4 having random no. b/w 1 to 10
    
    # np.full([m,n],any data)
     -> return array of size m,n full with data given

    # np.arange(1,5) or np.arange(m,n->exclude)
     -> return array [1,2,3,4]
    
    # np. arange(0,10,2) or np.arange(start,end,skip)
     -> retrun array by skipping the given size     
    
    # np.linspace(0,10,6) or np.linspace(range,parts)
     -> return array of 6 number b/w 1 to 10 haivng equal differece

In [ ]:
ar1 = np.zeros([3,2]) 
print(ar1)

ar2 = np.random.random([3,2])
print(ar2)
      
ar3 = np.random.randint(1,10)
print(ar3)
     
ar4 = np.random.randint(1,10,[3,4])
print(ar4)
     
ar5 =  np.full([3,5],7)
print(ar5)
ar6 =  np.full([3,5],'h')
print(ar6)
   
ar7 =  np.arange(1,5)
print(ar7)
    
ar8 =  np. arange(0,10,2)
print(ar8)
       
ar9 =  np.linspace(0,10,6)
print(ar9)
    

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.55380841 0.17962297]
 [0.65435525 0.90127407]
 [0.23921969 0.5146924 ]]
2
[[6 9 2 6]
 [7 9 4 8]
 [7 4 6 6]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[['h' 'h' 'h' 'h' 'h']
 ['h' 'h' 'h' 'h' 'h']
 ['h' 'h' 'h' 'h' 'h']]
[1 2 3 4]
[0 2 4 6 8]
[ 0.  2.  4.  6.  8. 10.]


#### Array Anatomy
     # Data type of arry,number of elemnet in array, number of dimension in array
      -> arr.dtype, arr.size, arr.ndim respectively
     
     # Produnct of rows and column is equal to size of array


In [9]:
arr = np.random.randint(1,50,[6,5])
print(arr)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

[[23 36 19 38 20]
 [ 1 22 40 41 46]
 [ 8 40 41 31 35]
 [44  1 23 13 27]
 [ 6 46  6 12  1]
 [ 3  7 33 44 37]]
int32
30
2


#### Reshape,Changing dimensions of Array
     # np.reshape(dimesnions)  where dimensions can be any = 2D,3D,4D............nD
      -> note product of dimension you creating is equal to size of array

     # Dot operator for execute many funtions
      -> np.arange(1,25).reshape(8,4)
      -> np.arange(1,13).reshape(3,4).dtype

In [ ]:
# suppose arr is array of size 24 elements
arr = np.arange(1,25)
print(arr)
print(arr.size)

ar1 = arr.reshape(6,4)  # size 6X4 = 24
print(ar1)

ar2 = arr.reshape(3,4,2) # size 3X4X2 = 24
print(ar2)

# Dot operator for execute many funtions
ar3 = np.arange(1,25).reshape(8,3)
print(ar3)

# note we are assign the result to a new array


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
24
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


#### Array Mathematics
    # Sum function only work with array and its axis
      -> Columns Sum axis - 0
      -> Rows sum axis - 1
    
    # Any other function of mathematics that fall under numpy only work with number 
      -> add, subtract, divide, multiply, log, exp, sqrt, sin, cos, tan

    # Function work on a paticlar array
      -> mean, max, min, var

In [ ]:
brr1 = np.array([[10,20],[30,40]])


In [ ]:
print(np.sum(brr1)) # total sum of all elements in a array
print(np.sum(brr1,axis = 0)) # sum column wise
print(np.sum(brr1,axis = 1)) # sum row wise



100
[40 60]
[30 70]


In [10]:
print(np.mean(brr1))
print(np.min(brr1))
print(np.max(brr1))
print(np.var(brr1))

25.0
10
40
125.0


In [9]:
print(np.add(10,20))
print(np.subtract(100,20))
print(np.multiply(10,20))
print(np.divide(10,20))
print(np.log(20))
print(np.exp(20))
print(np.sqrt(20))
print(np.sin(20))
print(np.cos(20))

30
80
200
0.5
2.995732273553991
485165195.4097903
4.47213595499958
0.9129452507276277
0.40808206181339196


#### Taking Subset From Array
     -> Using slicing concept 
      -> arrray[start:end,start:end] ->  [for rows,for cols] , note-> end value does'nt include by default
    
     -> if start value is not mentioned, python considers 0 by default
     -> if end value is not mentioned it extract till the last"
        

In [11]:
brr2 = np.arange(1,25).reshape(6,4)
print(brr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [17]:
print(brr2[1:5,0:3])

print(brr2[2:6,0:4])
print(brr2[2:6,:4])
print(brr2[2:,:4])

# Q-> Extract from 2nd row till last row and all column

print(brr2[1:])

# Q-> Extract all rows and some columns
print(brr2[:,1:5])

[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]
[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]
 [22 23 24]]


#### Array Manipulation
    # Concatenate Vertically
     -> np.concatenate([ar1,ar2], axis = 0) 
     -> np.row_stack([ar1,ar2])
     -> np.vstack([ar1,ar2])

    # Concatenate Horizontally
     -> np.concatenate([ar1,ar2], axis = 1)
     -> np.column_stack([ar1,ar2])
     -> np.hstack([ar1,ar2])

In [18]:
ar1 = np.array([[10,20],[30,40]])
ar2 = np.array([[50,60],[70,80]])

print(np.concatenate([ar1,ar2], axis = 0))
print(np.row_stack([ar1,ar2]))
print(np.vstack([ar1,ar2]))

[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]


C:\Users\hardi\AppData\Local\Temp\ipykernel_20648\1921093561.py:5: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack([ar1,ar2]))


In [19]:
print(np.concatenate([ar1,ar2], axis = 1))
print(np.column_stack([ar1,ar2]))
print(np.hstack([ar1,ar2]))

[[10 20 50 60]
 [30 40 70 80]]
[[10 20 50 60]
 [30 40 70 80]]
[[10 20 50 60]
 [30 40 70 80]]


#### Splitting the Array
    # Horizonatal Splitting
     -> np.hsplit(array,size)

    # Vertical Splitting
     ->np.vsplit(array,size)

    # Note -> splitting the array according to size

In [20]:
ar3 = np.arange(1,13).reshape(2,6)
print(ar3)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [25]:
print(np.hsplit(ar3,3))
print(np.vsplit(ar3,2))

[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]
